name: frame_of_mind
on:
  push:
    branches:
      - 'production'
  workflow_dispatch:

env:
  POSTGRES_DB: bad_project
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

jobs:
  # testing:
  #   runs-on: ubuntu-latest
  #   container: node:latest
  #   services:
  #     postgres:
  #       image: postgres
  #       env: 
  #         POSTGRES_DB: ${{env.POSTGRES_DB}}
  #         POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
  #       ports:
  #         - 5432:5432
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: |
  #         npm install 
  #         npx knex migrate:latest --env test
  #         npx jest
  deploy:
    runs-on: ubuntu-latest
    # needs: testing
    steps:
    - name: ssh to pull latest version
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd c23-bad-project-03-tw
          git checkout production 
          git pull origin production
          yarn install
          yarn knex migrate:latest --env production
          forever restart 0
        host: frameofmind.dev.kayaleung.me
        user: ubuntu
        key: ${{secrets.SSH_PRIVATE_KEY}}
